All: ImageParser.class YoutubeParser.class
ImageParser.class: ImageParser.java
	javac -cp ../lib/htmlparser.jar:../lib/htmllexer.jar:../filterbuilder.jar:../sitecapturer.jar:thumbelina.jar:. ImageParser.java
YoutubeParser.class: YoutubeParser.java
	javac -cp ../lib/commons-codec-1.3.jar:../lib/commons-logging-1.1.1.jar:../lib/commons-httpclient-3.1.jar:. YoutubeParser.java
